name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run fix
      - run: yarn run stats
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      - run: yarn run build
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build
          git-config-name	: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
